"""add email details to user field

Revision ID: 7a21e17d4a91
Revises: 185f5d11e5f7
Create Date: 2022-06-16 14:20:07.829159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a21e17d4a91'
down_revision = '185f5d11e5f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('contact_me_general', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('contact_me_topic_chosen', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'contact_me_topic_chosen')
    op.drop_column('users', 'contact_me_general')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
